// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: member.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Member {
  public static partial class MemberService
  {
    static readonly string __ServiceName = "member.MemberService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Member.SignUpRequest> __Marshaller_member_SignUpRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Member.SignUpRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Member.SignUpResponse> __Marshaller_member_SignUpResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Member.SignUpResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Member.CheckDuplicateIdRequest> __Marshaller_member_CheckDuplicateIdRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Member.CheckDuplicateIdRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Member.CheckDuplicateIdResponse> __Marshaller_member_CheckDuplicateIdResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Member.CheckDuplicateIdResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Member.CheckDuplicateNicknameRequest> __Marshaller_member_CheckDuplicateNicknameRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Member.CheckDuplicateNicknameRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Member.CheckDuplicateNicknameResponse> __Marshaller_member_CheckDuplicateNicknameResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Member.CheckDuplicateNicknameResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Member.CheckDuplicateNicknameWithTokenRequest> __Marshaller_member_CheckDuplicateNicknameWithTokenRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Member.CheckDuplicateNicknameWithTokenRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Member.CheckDuplicateNicknameWithTokenResponse> __Marshaller_member_CheckDuplicateNicknameWithTokenResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Member.CheckDuplicateNicknameWithTokenResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Member.UpdateProfileRequest> __Marshaller_member_UpdateProfileRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Member.UpdateProfileRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Member.UpdateProfileResponse> __Marshaller_member_UpdateProfileResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Member.UpdateProfileResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Member.UpdateNicknameRequest> __Marshaller_member_UpdateNicknameRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Member.UpdateNicknameRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Member.UpdateNicknameResponse> __Marshaller_member_UpdateNicknameResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Member.UpdateNicknameResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Member.UpdatePasswordRequest> __Marshaller_member_UpdatePasswordRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Member.UpdatePasswordRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Member.UpdatePasswordResponse> __Marshaller_member_UpdatePasswordResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Member.UpdatePasswordResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Member.SignUpRequest, global::Member.SignUpResponse> __Method_SignUp = new grpc::Method<global::Member.SignUpRequest, global::Member.SignUpResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SignUp",
        __Marshaller_member_SignUpRequest,
        __Marshaller_member_SignUpResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Member.CheckDuplicateIdRequest, global::Member.CheckDuplicateIdResponse> __Method_CheckDuplicateId = new grpc::Method<global::Member.CheckDuplicateIdRequest, global::Member.CheckDuplicateIdResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CheckDuplicateId",
        __Marshaller_member_CheckDuplicateIdRequest,
        __Marshaller_member_CheckDuplicateIdResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Member.CheckDuplicateNicknameRequest, global::Member.CheckDuplicateNicknameResponse> __Method_CheckDuplicateNickname = new grpc::Method<global::Member.CheckDuplicateNicknameRequest, global::Member.CheckDuplicateNicknameResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CheckDuplicateNickname",
        __Marshaller_member_CheckDuplicateNicknameRequest,
        __Marshaller_member_CheckDuplicateNicknameResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Member.CheckDuplicateNicknameWithTokenRequest, global::Member.CheckDuplicateNicknameWithTokenResponse> __Method_CheckDuplicateNicknameWithToken = new grpc::Method<global::Member.CheckDuplicateNicknameWithTokenRequest, global::Member.CheckDuplicateNicknameWithTokenResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CheckDuplicateNicknameWithToken",
        __Marshaller_member_CheckDuplicateNicknameWithTokenRequest,
        __Marshaller_member_CheckDuplicateNicknameWithTokenResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Member.UpdateProfileRequest, global::Member.UpdateProfileResponse> __Method_UpdateProfilePhoto = new grpc::Method<global::Member.UpdateProfileRequest, global::Member.UpdateProfileResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateProfilePhoto",
        __Marshaller_member_UpdateProfileRequest,
        __Marshaller_member_UpdateProfileResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Member.UpdateNicknameRequest, global::Member.UpdateNicknameResponse> __Method_UpdateNickname = new grpc::Method<global::Member.UpdateNicknameRequest, global::Member.UpdateNicknameResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateNickname",
        __Marshaller_member_UpdateNicknameRequest,
        __Marshaller_member_UpdateNicknameResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Member.UpdatePasswordRequest, global::Member.UpdatePasswordResponse> __Method_UpdatePassword = new grpc::Method<global::Member.UpdatePasswordRequest, global::Member.UpdatePasswordResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdatePassword",
        __Marshaller_member_UpdatePasswordRequest,
        __Marshaller_member_UpdatePasswordResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Member.MemberReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MemberService</summary>
    [grpc::BindServiceMethod(typeof(MemberService), "BindService")]
    public abstract partial class MemberServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Member.SignUpResponse> SignUp(global::Member.SignUpRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Member.CheckDuplicateIdResponse> CheckDuplicateId(global::Member.CheckDuplicateIdRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Member.CheckDuplicateNicknameResponse> CheckDuplicateNickname(global::Member.CheckDuplicateNicknameRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Member.CheckDuplicateNicknameWithTokenResponse> CheckDuplicateNicknameWithToken(global::Member.CheckDuplicateNicknameWithTokenRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Member.UpdateProfileResponse> UpdateProfilePhoto(global::Member.UpdateProfileRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Member.UpdateNicknameResponse> UpdateNickname(global::Member.UpdateNicknameRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Member.UpdatePasswordResponse> UpdatePassword(global::Member.UpdatePasswordRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MemberService</summary>
    public partial class MemberServiceClient : grpc::ClientBase<MemberServiceClient>
    {
      /// <summary>Creates a new client for MemberService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MemberServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MemberService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MemberServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MemberServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MemberServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Member.SignUpResponse SignUp(global::Member.SignUpRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SignUp(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Member.SignUpResponse SignUp(global::Member.SignUpRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SignUp, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Member.SignUpResponse> SignUpAsync(global::Member.SignUpRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SignUpAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Member.SignUpResponse> SignUpAsync(global::Member.SignUpRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SignUp, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Member.CheckDuplicateIdResponse CheckDuplicateId(global::Member.CheckDuplicateIdRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CheckDuplicateId(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Member.CheckDuplicateIdResponse CheckDuplicateId(global::Member.CheckDuplicateIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CheckDuplicateId, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Member.CheckDuplicateIdResponse> CheckDuplicateIdAsync(global::Member.CheckDuplicateIdRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CheckDuplicateIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Member.CheckDuplicateIdResponse> CheckDuplicateIdAsync(global::Member.CheckDuplicateIdRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CheckDuplicateId, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Member.CheckDuplicateNicknameResponse CheckDuplicateNickname(global::Member.CheckDuplicateNicknameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CheckDuplicateNickname(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Member.CheckDuplicateNicknameResponse CheckDuplicateNickname(global::Member.CheckDuplicateNicknameRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CheckDuplicateNickname, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Member.CheckDuplicateNicknameResponse> CheckDuplicateNicknameAsync(global::Member.CheckDuplicateNicknameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CheckDuplicateNicknameAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Member.CheckDuplicateNicknameResponse> CheckDuplicateNicknameAsync(global::Member.CheckDuplicateNicknameRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CheckDuplicateNickname, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Member.CheckDuplicateNicknameWithTokenResponse CheckDuplicateNicknameWithToken(global::Member.CheckDuplicateNicknameWithTokenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CheckDuplicateNicknameWithToken(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Member.CheckDuplicateNicknameWithTokenResponse CheckDuplicateNicknameWithToken(global::Member.CheckDuplicateNicknameWithTokenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CheckDuplicateNicknameWithToken, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Member.CheckDuplicateNicknameWithTokenResponse> CheckDuplicateNicknameWithTokenAsync(global::Member.CheckDuplicateNicknameWithTokenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CheckDuplicateNicknameWithTokenAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Member.CheckDuplicateNicknameWithTokenResponse> CheckDuplicateNicknameWithTokenAsync(global::Member.CheckDuplicateNicknameWithTokenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CheckDuplicateNicknameWithToken, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Member.UpdateProfileResponse UpdateProfilePhoto(global::Member.UpdateProfileRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateProfilePhoto(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Member.UpdateProfileResponse UpdateProfilePhoto(global::Member.UpdateProfileRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateProfilePhoto, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Member.UpdateProfileResponse> UpdateProfilePhotoAsync(global::Member.UpdateProfileRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateProfilePhotoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Member.UpdateProfileResponse> UpdateProfilePhotoAsync(global::Member.UpdateProfileRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateProfilePhoto, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Member.UpdateNicknameResponse UpdateNickname(global::Member.UpdateNicknameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateNickname(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Member.UpdateNicknameResponse UpdateNickname(global::Member.UpdateNicknameRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateNickname, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Member.UpdateNicknameResponse> UpdateNicknameAsync(global::Member.UpdateNicknameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateNicknameAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Member.UpdateNicknameResponse> UpdateNicknameAsync(global::Member.UpdateNicknameRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateNickname, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Member.UpdatePasswordResponse UpdatePassword(global::Member.UpdatePasswordRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdatePassword(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Member.UpdatePasswordResponse UpdatePassword(global::Member.UpdatePasswordRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdatePassword, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Member.UpdatePasswordResponse> UpdatePasswordAsync(global::Member.UpdatePasswordRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdatePasswordAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Member.UpdatePasswordResponse> UpdatePasswordAsync(global::Member.UpdatePasswordRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdatePassword, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override MemberServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MemberServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(MemberServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SignUp, serviceImpl.SignUp)
          .AddMethod(__Method_CheckDuplicateId, serviceImpl.CheckDuplicateId)
          .AddMethod(__Method_CheckDuplicateNickname, serviceImpl.CheckDuplicateNickname)
          .AddMethod(__Method_CheckDuplicateNicknameWithToken, serviceImpl.CheckDuplicateNicknameWithToken)
          .AddMethod(__Method_UpdateProfilePhoto, serviceImpl.UpdateProfilePhoto)
          .AddMethod(__Method_UpdateNickname, serviceImpl.UpdateNickname)
          .AddMethod(__Method_UpdatePassword, serviceImpl.UpdatePassword).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MemberServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SignUp, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Member.SignUpRequest, global::Member.SignUpResponse>(serviceImpl.SignUp));
      serviceBinder.AddMethod(__Method_CheckDuplicateId, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Member.CheckDuplicateIdRequest, global::Member.CheckDuplicateIdResponse>(serviceImpl.CheckDuplicateId));
      serviceBinder.AddMethod(__Method_CheckDuplicateNickname, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Member.CheckDuplicateNicknameRequest, global::Member.CheckDuplicateNicknameResponse>(serviceImpl.CheckDuplicateNickname));
      serviceBinder.AddMethod(__Method_CheckDuplicateNicknameWithToken, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Member.CheckDuplicateNicknameWithTokenRequest, global::Member.CheckDuplicateNicknameWithTokenResponse>(serviceImpl.CheckDuplicateNicknameWithToken));
      serviceBinder.AddMethod(__Method_UpdateProfilePhoto, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Member.UpdateProfileRequest, global::Member.UpdateProfileResponse>(serviceImpl.UpdateProfilePhoto));
      serviceBinder.AddMethod(__Method_UpdateNickname, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Member.UpdateNicknameRequest, global::Member.UpdateNicknameResponse>(serviceImpl.UpdateNickname));
      serviceBinder.AddMethod(__Method_UpdatePassword, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Member.UpdatePasswordRequest, global::Member.UpdatePasswordResponse>(serviceImpl.UpdatePassword));
    }

  }
}
#endregion
